# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex_exponential.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='complex_exponential.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x19\x63omplex_exponential.proto\"\x1f\n\x08Question\x12\x13\n\x0bwhat_signal\x18\x01 \x01(\x08\"\x1d\n\x06\x41nswer\x12\x13\n\x0bsignal_name\x18\x01 \x03(\t\"H\n\x05Param\x12\x13\n\x0bsignal_name\x18\x01 \x01(\t\x12\x12\n\nphaseBegin\x18\x02 \x01(\x02\x12\x16\n\x0ephaseIncrement\x18\x03 \x01(\x02\"*\n\x07\x43onfirm\x12\x0c\n\x04okay\x18\x01 \x01(\x08\x12\x11\n\tnarrative\x18\x02 \x01(\t\"\x1d\n\x07Request\x12\x12\n\nnumSamples\x18\x01 \x01(\x05\"$\n\x06Sample\x12\x0c\n\x04real\x18\x01 \x03(\x02\x12\x0c\n\x04imag\x18\x02 \x03(\x02\x32r\n\x12\x43omplexExponential\x12\x1b\n\x05Query\x12\t.Question\x1a\x07.Answer\x12\x1d\n\tSetConfig\x12\x06.Param\x1a\x08.Confirm\x12 \n\tGetSignal\x12\x08.Request\x1a\x07.Sample0\x01\x62\x06proto3')
)




_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='what_signal', full_name='Question.what_signal', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=60,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal_name', full_name='Answer.signal_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)


_PARAM = _descriptor.Descriptor(
  name='Param',
  full_name='Param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signal_name', full_name='Param.signal_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phaseBegin', full_name='Param.phaseBegin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phaseIncrement', full_name='Param.phaseIncrement', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=165,
)


_CONFIRM = _descriptor.Descriptor(
  name='Confirm',
  full_name='Confirm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='okay', full_name='Confirm.okay', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='narrative', full_name='Confirm.narrative', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=209,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numSamples', full_name='Request.numSamples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=240,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='Sample.real', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imag', full_name='Sample.imag', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=278,
)

DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
DESCRIPTOR.message_types_by_name['Param'] = _PARAM
DESCRIPTOR.message_types_by_name['Confirm'] = _CONFIRM
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Question = _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), dict(
  DESCRIPTOR = _QUESTION,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Question)
  ))
_sym_db.RegisterMessage(Question)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Answer)
  ))
_sym_db.RegisterMessage(Answer)

Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), dict(
  DESCRIPTOR = _PARAM,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Param)
  ))
_sym_db.RegisterMessage(Param)

Confirm = _reflection.GeneratedProtocolMessageType('Confirm', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRM,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Confirm)
  ))
_sym_db.RegisterMessage(Confirm)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'complex_exponential_pb2'
  # @@protoc_insertion_point(class_scope:Sample)
  ))
_sym_db.RegisterMessage(Sample)



_COMPLEXEXPONENTIAL = _descriptor.ServiceDescriptor(
  name='ComplexExponential',
  full_name='ComplexExponential',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=280,
  serialized_end=394,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='ComplexExponential.Query',
    index=0,
    containing_service=None,
    input_type=_QUESTION,
    output_type=_ANSWER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetConfig',
    full_name='ComplexExponential.SetConfig',
    index=1,
    containing_service=None,
    input_type=_PARAM,
    output_type=_CONFIRM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSignal',
    full_name='ComplexExponential.GetSignal',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_SAMPLE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPLEXEXPONENTIAL)

DESCRIPTOR.services_by_name['ComplexExponential'] = _COMPLEXEXPONENTIAL

# @@protoc_insertion_point(module_scope)
