"""
The Python implementation of a generic GRPC service stub
Progammer David G Messerschmitt
19 Feb 2018
"""

from concurrent import futures
import time
import importlib

from PROTO_DEFINITIONS import *

# gRPC engine
import grpc

# Import gRPC-compiled modules with generic renaming                                  
grpcServe = importlib.import_module('{0}_pb2_grpc'.format(PROTO_FILE))
grpcServicer = getattr(grpcServe,'{0}Servicer'.format(SERVICE))
grpcAddServicer = getattr(grpcServe,'add_{0}Servicer_to_server'.format(SERVICE))

# Configuration
MAXIMUM_SERVICE_TIME_IN_MINUTES = 60

class GenericServer(grpcServicer):
  # initiate and run a server

  def __init__(self):

    # import and generically rename gRPC code generated by the .proto compiler
    self.message = importlib.import_module('{0}_pb2'.format(PROTO_FILE))

    # set False to force server termination at the next timeout opportunity
    self.going = True
    
    super().__init__()

  def run(self):

    s = grpc.server(futures.ThreadPoolExecutor(max_workers=10)) # instantiate server
    grpcAddServicer(self,s) # add server to pool
    s.add_insecure_port(NET_CONNECTION) # open network port to server

    # start server, stop when requested or following a timeout
    elapsed = 0 # elapsed time in minutes
    s.start()
    while self.going and elapsed < MAXIMUM_SERVICE_TIME_IN_MINUTES:
      time.sleep(60) # sleep for one minute
      elapsed += 1
    s.stop(0)


