# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import time_series_streaming_pb2 as time__series__streaming__pb2


class TimeSeriesStreamingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MetaDataCoordination = channel.unary_unary(
        '/TimeSeriesStreaming/MetaDataCoordination',
        request_serializer=time__series__streaming__pb2.Config.SerializeToString,
        response_deserializer=time__series__streaming__pb2.Info.FromString,
        )
    self.RealTimeSeries = channel.unary_stream(
        '/TimeSeriesStreaming/RealTimeSeries',
        request_serializer=time__series__streaming__pb2.Config.SerializeToString,
        response_deserializer=time__series__streaming__pb2.RealSample.FromString,
        )
    self.ComplexTimeSeries = channel.unary_stream(
        '/TimeSeriesStreaming/ComplexTimeSeries',
        request_serializer=time__series__streaming__pb2.Config.SerializeToString,
        response_deserializer=time__series__streaming__pb2.ComplexSample.FromString,
        )


class TimeSeriesStreamingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MetaDataCoordination(self, request, context):
    """Back-and-forth needed to coordinate server with client
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RealTimeSeries(self, request, context):
    """Signal consisting of a stream of real-valued samples
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ComplexTimeSeries(self, request, context):
    """Signal consisting of a stream of complex-valued samples
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TimeSeriesStreamingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MetaDataCoordination': grpc.unary_unary_rpc_method_handler(
          servicer.MetaDataCoordination,
          request_deserializer=time__series__streaming__pb2.Config.FromString,
          response_serializer=time__series__streaming__pb2.Info.SerializeToString,
      ),
      'RealTimeSeries': grpc.unary_stream_rpc_method_handler(
          servicer.RealTimeSeries,
          request_deserializer=time__series__streaming__pb2.Config.FromString,
          response_serializer=time__series__streaming__pb2.RealSample.SerializeToString,
      ),
      'ComplexTimeSeries': grpc.unary_stream_rpc_method_handler(
          servicer.ComplexTimeSeries,
          request_deserializer=time__series__streaming__pb2.Config.FromString,
          response_serializer=time__series__streaming__pb2.ComplexSample.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TimeSeriesStreaming', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
